namespace GK {

	public enum RoadShape {
		FROM_UP_TO_TURN_RIGHT_CORNER,
		FROM_UP_TO_TURN_LEFT_CORNER,
		FROM_RIGHT_TO_TURN_UP_CORNER,
		FROM_LEFT_TO_TURN_UP_CORNER,
		FROM_LEFT_TO_RIGHT_U_SHAPE,
		FROM_RIGHT_TO_LEFT_U_SHAPE,
		LEFT_STRAIGHT,
		RIGHT_STRAIGHT,
		UP_STRAIGHT
	}

}
